issue_tracker/urls.py
from django.conf import settings
from django.conf.urls.static import static

from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as auth_views
from users import views as user_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('issues.urls')),
    path('', include('projects.urls')),
    path('projects/', include('projects.urls')),
    path('users/register/', user_views.register, name='register'),
    path('users/login/', auth_views.LoginView.as_view(template_name='users/login.html'), name='login'),
    path('users/logout/', auth_views.LogoutView.as_view(template_name='users/logout.html'), name='logout'),
    path('password-reset/', auth_views.PasswordResetView.as_view(template_name='users/password_reset.html'),
         name='password_reset'),
    path('password-reset/done/', auth_views.PasswordResetDoneView.as_view(template_name='users/password_reset_done.html'),
         name='password_reset_done'),
    path('password-reset-complete/',
         auth_views.PasswordResetCompleteView.as_view(template_name='users/password_reset_complete.html'),
         name='password_reset_complete'),
    path('password-reset-confirm/confirm/<uidb64>/<token>/',
         auth_views.PasswordResetConfirmView.as_view(template_name='users/password_reset_confirm.html'),
         name='password_reset_confirm'),
    path('users/profile/', user_views.profile, name='profile'),

]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

issues/urls.py
from django.urls import path
from . import views
from .views import (
    IssueDetailView,
    IssueCreateView,
    IssueUpdateView,
    IssueDeleteView,
    UserIssueListView,
    ProjectIssueListView,
    ownership_view,
    load_hours_view,
    close_issue_view,
)
app_name = 'issues'
urlpatterns = [
    path('projects/<int:project_id>/issues/', ProjectIssueListView.as_view(), name='project-issues'),
    path('<str:username>/issues/', UserIssueListView.as_view(), name='user-issues'),
    path('projects/<int:project_id>/issues/<int:pk>/', IssueDetailView.as_view(), name='issue-detail'),
    path('projects/<int:project_id>/issues/new/', IssueCreateView.as_view(), name='issue-create'),
    path('projects/<int:project_id>/issues/<int:pk>/update/', IssueUpdateView.as_view(), name='issue-update'),
    path('projects/<int:project_id>/issues/<int:pk>/delete/', IssueDeleteView.as_view(), name='issue-delete'),
    path('projects/<int:project_id>/issues/<int:pk>/ownership/', ownership_view, name='issue-ownership'),
    path('projects/<int:project_id>/issues/<int:pk>/load-hours/', load_hours_view, name='issue-load-hours'),
    path('projects/<int:project_id>/issues/<int:pk>/close/', close_issue_view, name='issue-close'),

]

projects/urls.py
from django.urls import path
from . import views
from .views import (
    ProjectListView,
    ProjectDetailView,
    ProjectCreateView,
    ProjectUpdateView,
    ProjectDeleteView,
    UserProjectListView
)

app_name = 'projects'
urlpatterns = [
    path('', ProjectListView.as_view(), name='home'),
    path('user/<str:username>/', UserProjectListView.as_view(), name='user-projects'),
    path('<int:pk>/', ProjectDetailView.as_view(), name='project-detail'),
    path('new/', ProjectCreateView.as_view(), name='project-create'),
    path('<int:pk>/update/', ProjectUpdateView.as_view(), name='project-update'),
    path('<int:pk>/delete/', ProjectDeleteView.as_view(), name='project-delete'),
    path('about/', views.about, name='about'),
]

issues/models.py
from django.db import models
from django.utils import timezone
from enum import Enum
from django.contrib.auth.models import User
from projects.models import Project
from django.core.validators import MinValueValidator, MaxValueValidator
from django.urls import reverse


class IssueStatusChoices(Enum):
    CREATED = "CREATED"
    OPEN = "OPEN"
    ASSIGNED = "ASSIGNED"
    CLOSED = "CLOSED"

    @classmethod
    def choices(cls):
        return tuple((i.name, i.value) for i in cls)


class Issue(models.Model):
    project = models.ForeignKey(Project, on_delete=models.CASCADE)
    creator = models.ForeignKey(User, related_name="%(class)ss_created", on_delete=models.CASCADE)
    owner = models.ForeignKey(User, related_name="%(class)ss_owned", null=True, on_delete=models.SET_NULL, blank=True)
    users = models.ManyToManyField(User, related_name="%(class)ss_watched", blank=True)
    title = models.CharField(max_length=50)
    details = models.CharField(max_length=300)
    priority = models.IntegerField(null=False, default=5, validators=[MinValueValidator(1), MaxValueValidator(5)])
    created_on = models.DateTimeField(auto_now_add=True)
    updated_on = models.DateTimeField(auto_now=True)
    closed_on = models.DateTimeField(null=True, blank=True)
    status = models.CharField(default=IssueStatusChoices.CREATED.value, max_length=50, choices=IssueStatusChoices.choices())
    estimated_work_hours = models.IntegerField(null=True, validators=[MinValueValidator(0)])
    loaded_work_hours = models.IntegerField(default=0, validators=[MinValueValidator(0)])

    def __str__(self):
        return 'Issue ' + str(self.title) + ' created by ' + str(self.creator.username)

    def get_absolute_url(self):
        return reverse('issues:issue-detail', kwargs={'project_id': self.project.id, 'pk': self.pk})


class Comment(models.Model):
    issue = models.ForeignKey(Issue, on_delete=models.CASCADE)
    creator = models.ForeignKey(User, on_delete=models.CASCADE)
    title = models.CharField(max_length=50)
    content = models.CharField(max_length=300)
    created_on = models.DateTimeField(auto_now_add=True)
    updated_on = models.DateTimeField(auto_now=True)

    def __str__(self):
        return 'Comment ' + str(self.title) + ' created by ' + str(self.creator.username)

issues/forms.py
from django import forms
from .models import Issue


class IssueForm(forms.ModelForm):

    class Meta:
        model = Issue
        fields = ['title',
                  'details',
                  'priority',
                  'owner',
                  'users',
                  'estimated_work_hours',
                  ]
        labels = {
            'users': 'Observers'
        }
        widgets = {
            'users': forms.CheckboxSelectMultiple(),
        }

issues/views.py
from django.shortcuts import render, get_object_or_404
from django.contrib.auth.models import User
from projects.models import Project
from .models import Issue, IssueStatusChoices
from django.urls import reverse_lazy
from django.views.generic import (
    ListView,
    DetailView,
    CreateView,
    UpdateView,
    DeleteView
)
from .forms import IssueForm
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.contrib import messages
from django.http import HttpResponseRedirect


class IssueDetailView(UserPassesTestMixin, DetailView):
    model = Issue

    def test_func(self):
        if self.request.user in self.get_object().users.all() \
                or self.request.user == self.get_object().creator \
                or self.request.user == self.get_object().owner:
            return True
        return False


class UserIssueListView(ListView):
    model = Issue
    ordering = ['-created_on']
    template_name = 'issues/user_issues.html'
    paginate_by = 4

    def get_queryset(self):
        user = get_object_or_404(User, username=self.kwargs['username'])
        return Issue.objects.filter(owner=user).order_by('-created_on')


class ProjectIssueListView(ListView):
    model = Issue
    ordering = ['-created_on']
    template_name = 'issues/project_issues.html'
    paginate_by = 4

    def get_context_data(self, **kwargs):
        # Call the base implementation first to get a context
        context = super(ProjectIssueListView, self).get_context_data(**kwargs)
        context['project'] = Project.objects.get(pk=self.kwargs.get('project_id'))
        return context

    def get_queryset(self):
        project = get_object_or_404(Project, id=self.kwargs.get('project_id'))
        return Issue.objects.filter(project=project).order_by('-created_on')


class IssueCreateView(LoginRequiredMixin, CreateView):
    model = Issue
    form_class = IssueForm

    def form_valid(self, form):
        form.instance.project = get_object_or_404(Project, pk=self.kwargs['project_id'])
        form.instance.creator = self.request.user

        return super().form_valid(form)


class IssueUpdateView(LoginRequiredMixin, UserPassesTestMixin, UpdateView):
    model = Issue
    form_class = IssueForm

    def test_func(self):
        issue = self.get_object()
        if self.request.user == issue.creator:
            return True
        return False


class IssueDeleteView(LoginRequiredMixin, UserPassesTestMixin, DeleteView):
    model = Issue

    def test_func(self):
        issue = self.get_object()
        if self.request.user == issue.creator:
            return True
        return False

    def get_success_url(self):
        return reverse_lazy('issues:project-issues', kwargs={'project_id': self.object.project.pk})


def ownership_view(request, project_id, pk):
    issue = get_object_or_404(Issue, pk=pk)
    if not issue.owner:
        if request.method == "POST":
            issue.owner = request.user
            issue.status = IssueStatusChoices.ASSIGNED.value
            issue.save()
            messages.info(request, 'You have taken ownership successfully')
            return HttpResponseRedirect(
                reverse_lazy('issues:issue-detail', kwargs={'project_id': project_id, 'pk': pk}))
        else:
            context = {}
            context['project_id'] = project_id
            context['pk'] = pk
            context['issue'] = issue
            return render(request, 'issues/confirm_ownership.html', context)
    else:
        messages.warning(request, 'This issue already has an owner')
    return HttpResponseRedirect(reverse_lazy('issues:project-issues', kwargs={'project_id': project_id}))


def load_hours_view(request, project_id, pk):
    issue = get_object_or_404(Issue, pk=pk)
    if request.method == "POST":
        if request.user == issue.owner:
            input_hours = int(request.POST.get('hours'))
            if input_hours >= 0:
                issue.loaded_work_hours += input_hours
                issue.save()
                messages.info(request, "You have loaded hours to this Issue")
            else:
                messages.warning(request, "You can't load negative hours")
        else:
            messages.warning(request, "You can't load hours if you are not the issue's owner")
        return HttpResponseRedirect(reverse_lazy('issues:issue-detail', kwargs={'project_id': project_id, 'pk': pk}))
    else:
        context = {}
        context['project_id'] = project_id
        context['pk'] = pk
        context['issue'] = issue
    return render(request, "issues/issue_confirm_load_hours.html", context)


def close_issue_view(request, project_id, pk):
    issue = get_object_or_404(Issue, pk=pk)
    if issue.owner == request.user:
        if request.method == "POST":
            issue.status = IssueStatusChoices.CLOSED.value
            issue.save()
            messages.info(request, 'You have closed the issue')
            return HttpResponseRedirect(
                reverse_lazy('issues:project-issues', kwargs={'project_id': project_id}))
        else:
            context = {}
            context['project_id'] = project_id
            context['pk'] = pk
            context['issue'] = issue
            return render(request, 'issues/issue_confirm_close.html', context)
    else:
        messages.warning(request, "The issue can only be closed by its owner")
    return HttpResponseRedirect(reverse_lazy('issues:project-issues', kwargs={'project_id': project_id}))


def about(request):
    return render(request, 'issues/about.html', {'title': 'about'})

issues/templates/issues/confirm_ownership.html
{% extends "base.html" %}
{% block content %}
    <div class="content-section">
        <form method="POST">
            {% csrf_token %}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Take ownership</legend>
                <h2>Are you sure you want to be the owner of the issue: </h2>
                <h3><i>"{{ issue.title }}"</i></h3>
            </fieldset>
            <div class="form-group">
                <button class="btn btn-outline-danger" type="submit">Yes, Confirm</button>
                <a class="btn btn-outline-secondary" href="{% url 'issues:issue-detail' project_id=project_id pk=pk %}">Cancel</a>
            </div>
        </form>
    </div>
{% endblock content %}

issues/templates/issues/issue_confirm_close.html
{% extends "base.html" %}
{% block content %}
    <div class="content-section">
        <form method="POST">
            {% csrf_token %}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Close Issue</legend>
                <h2>Are you sure you want to close the issue: </h2>
                <h3><i>"{{ issue.title }}"</i></h3>
            </fieldset>
            <div class="form-group">
                <button class="btn btn-outline-danger" type="submit">Yes, Confirm</button>
                <a class="btn btn-outline-secondary" href="{% url 'issues:issue-detail' project_id=project_id pk=pk %}">Cancel</a>
            </div>
        </form>
    </div>
{% endblock content %}

issues/templates/issues/issue_confirm_delete.html
{% extends "base.html" %}
{% block content %}
    <div class="content-section">
        <form method="POST">
            {% csrf_token %}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Delete Issue</legend>
                <h2>Are you sure you want to delete the issue: </h2>
                <h3><i>"{{ object.title }}"</i></h3>
            </fieldset>
            <div class="form-group">
                <button class="btn btn-outline-danger" type="submit">Yes, Delete</button>
                <a class="btn btn-outline-secondary" href="{% url 'projects:project-detail' object.id %}">Cancel</a>
            </div>
        </form>
    </div>
{% endblock content %}

issues/templates/issues/issue_confirm_load_hours.html
{% extends "base.html" %}
{% block content %}
<div class="content-section">
    <form method="POST">
        {% csrf_token %}
        <fieldset class="form-group">
            <legend class="border-bottom mb-4">Load Work</legend>
            <h2>You are loading hours to issue "{{ issue.title }}"</h2>
            <div style="display: flex;">
                <h5 style="margin-right: 10px;"><i>Hours to load:</i></h5>
                <input type="number" name="hours" style="border-radius: 5px;"></input>
            </div>
        </fieldset>
        <div class="form-group">
            <button class="btn btn-outline-danger" type="submit">Yes, Confirm</button>
            <a class="btn btn-outline-secondary" href="{% url 'issues:issue-detail' project_id=project_id pk=pk %}">Cancel</a>
        </div>
    </form>
</div>
{% endblock content %}

issues/templates/issues/issue_detail.html
{% extends "base.html" %}
{% block content %}
<project class="media content-section">
    <div class="media-body">
        <div class="project-metadata">
            <a class="mr-2" href="#">{{ object.creator }}</a>
            <small class="text-muted">{{ object.created_on|date:"d-m-Y" }}</small>
            {% if object.creator == user or object.owner == user %}
            <div>
                <a class="btn btn-secondary btn-sm mt-1 mb-1"
                   href="{% url 'issues:issue-update' project_id=object.project.id pk=object.pk %}">Update</a>
                <a class="btn btn-danger btn-sm mt-1 mb-1"
                   href="{% url 'issues:issue-delete' project_id=object.project.id pk=object.pk %}">Delete</a>
                <object align="right"><a class="btn btn-secondary btn-sm mt-1 mb-1"
                                         href="{% url 'issues:project-issues' project_id=object.project.id %}">&laquo;
                    Back to Project</a></object>
            </div>
            {% endif %}
        </div>
        <h2 class="project-title">{{ object.title }}</h2>
        <div class="attribute-item">
            <big>{{ object.details }}</big>
        </div>
        <div class="attribute-item">
            <h4>Priority {{ object.priority }}</h4>
        </div>
        <div class="attribute-item">
            <h4>Status: {{ object.status }}</h4>
        </div>
        <div class="attribute-item">
            <h4>Estimated work hours: {{ object.estimated_work_hours }}</h4>
        </div>
        <div class="attribute-item" style="display: flex; justify-content: space-between;">
            <h4>Hours Loaded: {{ object.loaded_work_hours }}</h4>
            <a class="btn btn-secondary btn-sm mt-1 mb-1" style="self-align: right;"
               href="{% url 'issues:issue-load-hours' project_id=object.project.id pk=object.pk %}">Load Hours To Issue</a>
        </div>
        <div id="close-issue">
            <a class="btn btn-danger btn-sm mt-1 mb-1"
               href="{% url 'issues:issue-close' project_id=object.project.id pk=object.pk %}">Close Issue</a>
        </div>
    </div>

</project>
{% endblock content %}

issues/templates/issues/issue_form.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% block content %}
<form method="POST">
    {% csrf_token %}
    <fieldset class="form-group">
        <legend class="border-bottom mb-4">New Issue</legend>
        {{ form|crispy }}
    </fieldset>
    <div class="form-group">
        <button class="btn btn-outline-info" type="submit">Post</button>
    </div>
</form>
{% endblock content %}

issues/templates/issues/project_issues.html
{% extends "base.html" %}
{% block content %}
{% if object_list %}
<project class="media content-section">
    <div class="media-body">
        <div>
            <a class="mr-2" href="{% url 'projects:user-projects' username=project.creator.username %}">{{ project.creator }}</a>
            <small class="text-muted">{{ project.created_on|date:"d-m-Y" }}</small>
            {% if project.creator == user %}
            <div>
                <a class="btn btn-secondary btn-sm mt-1 mb-1"
                   href="{% url 'projects:project-update' project.pk %}">Update</a>
                <a class="btn btn-danger btn-sm mt-1 mb-1"
                   href="{% url 'projects:project-delete' project.pk %}">Delete</a>
                <a class="btn btn-secondary btn-sm mt-1 mb-1"
                   href="{% url 'issues:issue-create' project_id=project.pk %}">Create Issue</a>
            </div>
            {% endif %}
            <div class="attribute-item">
                <h2 class="project-title">{{ project.title }}</h2>
                <p class="project-content">{{ project.description }}</p>
            </div>

            <p style="margin-top: 15px; text-align:center;">Project's progress</p>
            <div id="progressbar" >
                <div style=" width: {{ project.progress_percentage  }}%;">
                    {{ project.progress_percentage }}%</div>
            </div>

        <div style="margin-bottom: 10px; margin-top: 15px;">
            <ul>
                {% for key, value in project.project_issues_status.items %}
            <li class="list-group-item list-group-item-light"> {{ key|lower|capfirst }} Issues: {{value}}</li>
                {% endfor %}
            </ul>
        </div>

        <div class="media-body">
            {% for object in object_list %}
            {% if object.status != "CLOSED" %}
            <project class="media content-section">
                {% if object.owner %}
                <div class="img-with-text">
                    <img class="rounded-circle account-img" src="{{ object.owner.profile.image.url }}">
                    <small class="text-muted"><a href="{% url 'issues:user-issues' object.owner.username %}">Owner: {{ object.owner }}</a></small>
                </div>
                {% endif %}
                {% for user in object.users.all %}
                <div class="img-with-text">
                    <img class="rounded-circle small-account-img" src="{{ user.profile.image.url }}">
                    <small class="text-muted">{{ user }}</small>
                </div>
                {% endfor %}
                <div class="media-body">
                    <div class="project-metadata">
                        <a class="mr-2" href="{% url 'issues:user-issues' object.creator.username %}">
                            <center>Created by {{ object.creator }}</center>
                        </a>

                    </div>
                    <h2 class="project-title"><a
                            href="{% url 'issues:issue-detail' project_id=object.project.id pk=object.pk %}">
                        <center>{{ object.title }}</center>
                    </a>
                    </h2>
                    <small><center>Status: {{ object.status }}</center></small>
                    {% if user.is_authenticated %}
                    <div align="right">
                        <a class="btn btn-secondary btn-sm mt-1 mb-1"
                        href="{% url 'issues:issue-ownership'  project_id=project.pk pk=object.pk %}">Take Ownership</a>
                    </div>
                    {% endif %}
                </div>
            </project>
            {% endif %}
            {% endfor %}
        </div>
    </div>
    </div>
</project>
{% else %}
    <h1>This project has no issues yet</h1>
    {% if project.creator == user %}
    <div>
        <a class="btn btn-secondary btn-sm mt-1 mb-1" href="{% url 'projects:project-update' project.id %}">Update</a>
        <a class="btn btn-danger btn-sm mt-1 mb-1" href="{% url 'projects:project-delete' project.id %}">Delete</a>
        <a class="btn btn-secondary btn-sm mt-1 mb-1" href="{% url 'issues:issue-create' project_id=project.id %}">Create Issue</a>
    </div>
    {% endif %}
{% endif %}

{% if is_paginated %}
    {% if page_obj.has_previous %}
        <a class="btn btn-outline-info mb-4" href="?page=1">First</a>
        <a class="btn btn-outline-info mb-4" href="?page={{ page_obj.previous_page_number }}">Previous</a>
    {% endif %}
    {% for num in page_obj.paginator.page_range %}
        {% if page_obj.number == num %}
            <a class="btn btn-info mb-4" href="?page={{ num }}">{{ num }}</a>
        {% elif num > page_obj.number|add:'-3' and num < page_obj.number|add:'3' %}
            <a class="btn btn-outline-info mb-4" href="?page={{ num }}">{{ num }}</a>
        {% endif %}
    {% endfor %}
    {% if page_obj.has_next %}
        <a class="btn btn-outline-info mb-4" href="?page={{ page_obj.next_page_number }}">Next</a>
        <a class="btn btn-outline-info mb-4" href="?page={{ page_obj.paginator.num_pages }}">Last</a>
    {% endif %}
{% endif %}
{% endblock content %}

issues/templates/issues/user_issues.html
{% extends "base.html" %}
{% block content %}
<div>
    <h1>Issues owned by {{ view.kwargs.username }} <span class="badge badge-secondary">{{ page_obj.paginator.count }}</span></h1>
</div>
<div>
    <a class="btn btn-secondary btn-sm mt-1 mb-1" href="{% url 'projects:user-projects' view.kwargs.username %}">{{ view.kwargs.username }}'s Projects</a>
</div>
{% for issue in object_list %}
<project class="media content-section">
    <img class="rounded-circle account-img" src="{{ issue.owner.profile.image.url }}">
    <div class="media-body">
        <div class="project-metadata">
            <a class="mr-2" href="{% url 'issues:user-issues' username=issue.owner.username %}">{{ issue.owner }}</a>
        </div>
        <h3><a class="project-title" href="{% url 'issues:issue-detail' project_id=issue.project.id pk=issue.pk %}">{{ issue.title }}</a></h3>
        <p class="project-content">{{ issue.description }}</p>
    </div>
</project>
{% endfor %}
{% if is_paginated %}
    {% if page_obj.has_previous %}
        <a class="btn btn-outline-info mb-4" href="?page=1">First</a>
        <a class="btn btn-outline-info mb-4" href="?page={{ page_obj.previous_page_number }}">Previous</a>
    {% endif %}
    {% for num in page_obj.paginator.page_range %}
        {% if page_obj.number == num %}
            <a class="btn btn-info mb-4" href="?page={{ num }}">{{ num }}</a>
        {% elif num > page_obj.number|add:'-3' and num < page_obj.number|add:'3' %}
            <a class="btn btn-outline-info mb-4" href="?page={{ num }}">{{ num }}</a>
        {% endif %}
    {% endfor %}
    {% if page_obj.has_next %}
        <a class="btn btn-outline-info mb-4" href="?page={{ page_obj.next_page_number }}">Next</a>
        <a class="btn btn-outline-info mb-4" href="?page={{ page_obj.paginator.num_pages }}">Last</a>
    {% endif %}
{% endif %}
{% endblock content %}