issue_tracker/urls.py
from django.conf import settings
from django.conf.urls.static import static

from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as auth_views
from users import views as user_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('issues.urls')),
    path('', include('projects.urls')),
    path('projects/', include('projects.urls')),
    path('users/register/', user_views.register, name='register'),
    path('users/login/', auth_views.LoginView.as_view(template_name='users/login.html'), name='login'),
    path('users/logout/', auth_views.LogoutView.as_view(template_name='users/logout.html'), name='logout'),
    path('password-reset/', auth_views.PasswordResetView.as_view(template_name='users/password_reset.html'),
         name='password_reset'),
    path('password-reset/done/', auth_views.PasswordResetDoneView.as_view(template_name='users/password_reset_done.html'),
         name='password_reset_done'),
    path('password-reset-complete/',
         auth_views.PasswordResetCompleteView.as_view(template_name='users/password_reset_complete.html'),
         name='password_reset_complete'),
    path('password-reset-confirm/confirm/<uidb64>/<token>/',
         auth_views.PasswordResetConfirmView.as_view(template_name='users/password_reset_confirm.html'),
         name='password_reset_confirm'),
    path('users/profile/', user_views.profile, name='profile'),

]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

issues/urls.py
from django.urls import path
from . import views
from .views import (
    IssueDetailView,
    IssueCreateView,
    IssueUpdateView,
    IssueDeleteView,
    UserIssueListView,
    ProjectIssueListView,
    ownership_view,
    load_hours_view,
    close_issue_view,
)
app_name = 'issues'
urlpatterns = [
    path('projects/<int:project_id>/issues/', ProjectIssueListView.as_view(), name='project-issues'),
    path('<str:username>/issues/', UserIssueListView.as_view(), name='user-issues'),
    path('projects/<int:project_id>/issues/<int:pk>/', IssueDetailView.as_view(), name='issue-detail'),
    path('projects/<int:project_id>/issues/new/', IssueCreateView.as_view(), name='issue-create'),
    path('projects/<int:project_id>/issues/<int:pk>/update/', IssueUpdateView.as_view(), name='issue-update'),
    path('projects/<int:project_id>/issues/<int:pk>/delete/', IssueDeleteView.as_view(), name='issue-delete'),
    path('projects/<int:project_id>/issues/<int:pk>/ownership/', ownership_view, name='issue-ownership'),
    path('projects/<int:project_id>/issues/<int:pk>/load-hours/', load_hours_view, name='issue-load-hours'),
    path('projects/<int:project_id>/issues/<int:pk>/close/', close_issue_view, name='issue-close'),

]

projects/urls.py
from django.urls import path
from . import views
from .views import (
    ProjectListView,
    ProjectDetailView,
    ProjectCreateView,
    ProjectUpdateView,
    ProjectDeleteView,
    UserProjectListView
)

app_name = 'projects'
urlpatterns = [
    path('', ProjectListView.as_view(), name='home'),
    path('user/<str:username>/', UserProjectListView.as_view(), name='user-projects'),
    path('<int:pk>/', ProjectDetailView.as_view(), name='project-detail'),
    path('new/', ProjectCreateView.as_view(), name='project-create'),
    path('<int:pk>/update/', ProjectUpdateView.as_view(), name='project-update'),
    path('<int:pk>/delete/', ProjectDeleteView.as_view(), name='project-delete'),
    path('about/', views.about, name='about'),
]

issues/models.py
from django.db import models
from django.utils import timezone
from enum import Enum
from django.contrib.auth.models import User
from projects.models import Project
from django.core.validators import MinValueValidator, MaxValueValidator
from django.urls import reverse


class IssueStatusChoices(Enum):
    CREATED = "CREATED"
    OPEN = "OPEN"
    ASSIGNED = "ASSIGNED"
    CLOSED = "CLOSED"

    @classmethod
    def choices(cls):
        return tuple((i.name, i.value) for i in cls)


class Issue(models.Model):
    project = models.ForeignKey(Project, on_delete=models.CASCADE)
    creator = models.ForeignKey(User, related_name="%(class)ss_created", on_delete=models.CASCADE)
    owner = models.ForeignKey(User, related_name="%(class)ss_owned", null=True, on_delete=models.SET_NULL, blank=True)
    users = models.ManyToManyField(User, related_name="%(class)ss_watched", blank=True)
    title = models.CharField(max_length=50)
    details = models.CharField(max_length=300)
    priority = models.IntegerField(null=False, default=5, validators=[MinValueValidator(1), MaxValueValidator(5)])
    created_on = models.DateTimeField(auto_now_add=True)
    updated_on = models.DateTimeField(auto_now=True)
    closed_on = models.DateTimeField(null=True, blank=True)
    status = models.CharField(default=IssueStatusChoices.CREATED.value, max_length=50, choices=IssueStatusChoices.choices())
    estimated_work_hours = models.IntegerField(null=True, validators=[MinValueValidator(0)])
    loaded_work_hours = models.IntegerField(default=0, validators=[MinValueValidator(0)])

    def __str__(self):
        return 'Issue ' + str(self.title) + ' created by ' + str(self.creator.username)

    def get_absolute_url(self):
        return reverse('issues:issue-detail', kwargs={'project_id': self.project.id, 'pk': self.pk})


class Comment(models.Model):
    issue = models.ForeignKey(Issue, on_delete=models.CASCADE)
    creator = models.ForeignKey(User, on_delete=models.CASCADE)
    title = models.CharField(max_length=50)
    content = models.CharField(max_length=300)
    created_on = models.DateTimeField(auto_now_add=True)
    updated_on = models.DateTimeField(auto_now=True)

    def __str__(self):
        return 'Comment ' + str(self.title) + ' created by ' + str(self.creator.username)

projects/models.py
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse


class Project(models.Model):
    title = models.CharField(max_length=50)
    creator = models.ForeignKey(User, on_delete=models.CASCADE)
    description = models.CharField(max_length=300)
    created_on = models.DateTimeField(auto_now_add=True)
    updated_on = models.DateTimeField(auto_now=True)

    def __str__(self):
        return 'Project ' + str(self.title) + ' created by ' + str(self.creator.username)

    def estimated_work_hours(self):
        total = 0
        sum_hours = sum([issue.estimated_work_hours for issue in self.issue_set.all()])
        if sum_hours == 0:
            raise ValueError("The estimated total work hours in this project are equal to 0")
        return sum_hours

    def loaded_work_hours(self):
        return sum([issue.loaded_work_hours for issue in self.issue_set.all()])

    def progress_percentage(self):
        try:
            progress = int((self.loaded_work_hours() / self.estimated_work_hours()) * 100)
            if progress < 100:
                return progress
            return 100
        except ValueError:
            return 0

    def project_issues_status(self):
        status_count = {}
        for issue in self.issue_set.all():
            if issue.status in status_count:
                status_count[issue.status] += 1
            else:
                status_count[issue.status] = 1
        return status_count

    def get_absolute_url(self):
        return reverse('projects:project-detail', kwargs={'pk': self.pk})

projects/views.py
from django.shortcuts import render, get_object_or_404
from django.contrib.auth.models import User
from .models import Project
from django.urls import reverse_lazy
from django.views.generic import (
    ListView,
    DetailView,
    CreateView,
    UpdateView,
    DeleteView
)
from projects import urls
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin


def home(request):
    context = {
        'projects': Project.objects.all()
    }
    return render(request, 'projects/home.html', context)


class ProjectListView(ListView):
    model = Project
    template_name = 'projects/home.html'
    context_object_name = 'projects'
    ordering = ['-created_on']
    paginate_by = 4


class UserProjectListView(ListView):
    model = Project
    template_name = 'projects/user_projects.html'
    context_object_name = 'projects'
    paginate_by = 4

    def get_queryset(self):
        user = get_object_or_404(User, username=self.kwargs.get('username'))
        return Project.objects.filter(creator=user).order_by('-created_on')


class ProjectDetailView(DetailView):
    model = Project


class ProjectCreateView(LoginRequiredMixin, CreateView):
        model = Project
        fields = ['title', 'description', ]

        def form_valid(self, form):
            form.instance.creator = self.request.user
            return super().form_valid(form)


class ProjectUpdateView(LoginRequiredMixin, UserPassesTestMixin, UpdateView):
    model = Project
    fields = ['title', 'description', ]

    def test_func(self):
        project = self.get_object()
        if self.request.user == project.creator:
            return True
        return False


class ProjectDeleteView(LoginRequiredMixin, UserPassesTestMixin, DeleteView):
    model = Project
    success_url = reverse_lazy('projects:home')

    def test_func(self):
        project = self.get_object()
        if self.request.user == project.creator:
            return True
        return False


def about(request):
    return render(request, 'projects/about.html', {'title': 'about'})

projects/templates/projects/about.html
{% extends "base.html" %}
{% block content %}
    <h1>About this site</h1>
    <big> This is an issue tracker app, it allows you to control your workflow by creating projects and issues.
        Issues have estimated hours for completion, an owner can be assigned to work on the issue, and he can load
        the hours worked
    </big>
<div>
    <small>For more info contact me <a href = "mailto:lucianopereira9555@gmail.com"><span>&#9993;</span></a></small>
</div>
{% endblock content %}

projects/templates/projects/detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Poll Question {{question.id}}</title>
</head>
<body>
<h1>{{ question.question_text }}</h1>
{% if error_message %}
    <p><strong>{{ error_message }}</strong></p>
{% endif %}

<form action="{% url 'polls:vote' question.id %}" method="post">
{% csrf_token %}
{% for choice in question.choice_set.all %}
    <input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}">
    <label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label><br>
{% endfor %}
<input type="submit" value="Vote">
</form>
</body>
</html>

projects/templates/projects/home.html
{% extends "base.html" %}
{% block content %}
{% for project in projects %}
<project class="media content-section">
    <img class="rounded-circle account-img" src="{{ project.creator.profile.image.url }}">
    <div class="media-body">
        <div class="project-metadata">
            <a class="mr-2" href="{% url 'projects:user-projects' username=project.creator.username %}" >{{ project.creator }}</a>
        </div>
        <h3><a class="project-title" href="{% url 'issues:project-issues' project.pk %}">{{ project.title }}</a></h3>
        <p class="project-content">{{ project.description }}</p>
    </div>
</project>
{% endfor %}
{% if is_paginated %}
    {% if page_obj.has_previous %}
        <a class="btn btn-outline-info mb-4" href="?page=1">First</a>
        <a class="btn btn-outline-info mb-4" href="?page={{ page_obj.previous_page_number }}">Previous</a>
    {% endif %}
    {% for num in page_obj.paginator.page_range %}
        {% if page_obj.number == num %}
            <a class="btn btn-info mb-4" href="?page={{ num }}">{{ num }}</a>
        {% elif num > page_obj.number|add:'-3' and num < page_obj.number|add:'3' %}
            <a class="btn btn-outline-info mb-4" href="?page={{ num }}">{{ num }}</a>
        {% endif %}
    {% endfor %}
    {% if page_obj.has_next %}
        <a class="btn btn-outline-info mb-4" href="?page={{ page_obj.next_page_number }}">Next</a>
        <a class="btn btn-outline-info mb-4" href="?page={{ page_obj.paginator.num_pages }}">Last</a>
    {% endif %}
{% endif %}
{% endblock content %}

projects/templates/projects/project_confirm_delete.html
{% extends "base.html" %}
{% block content %}
    <div class="content-section">
        <form method="POST">
            {% csrf_token %}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Delete Project</legend>
                <h2>Are you sure you want to delete the project: </h2>
                <h3><i>"{{ object.title }}"</i></h3>
            </fieldset>
            <div class="form-group">
                <button class="btn btn-outline-danger" type="submit">Yes, Delete</button>
                <a class="btn btn-outline-secondary" href="{% url 'projects:project-detail' object.id %}">Cancel</a>
            </div>
        </form>
    </div>
{% endblock content %}

projects/templates/projects/project_detail.html
{% extends "base.html" %}
{% block content %}
<project class="media content-section">
    <div class="media-body">
        <div class="project-metadata">
            <a class="mr-2" href="{% url 'projects:user-projects' username=object.creator.username %}">{{ object.creator }}</a>
            <small class="text-muted">{{ object.created_on|date:"d-m-Y" }}</small>
            {% if object.creator == user %}
            <div>
                <a class="btn btn-secondary btn-sm mt-1 mb-1" href="{% url 'projects:project-update' object.pk %}">Update</a>
                <a class="btn btn-danger btn-sm mt-1 mb-1" href="{% url 'projects:project-delete' object.pk %}">Delete</a>
                <a class="btn btn-secondary btn-sm mt-1 mb-1" href="{% url 'issues:issue-create' project_id=object.pk %}">Create Issue</a>

            </div>
            {% endif %}
        </div>
        <h2 class="project-title">{{ object.title }}</h2>
        <p class="project-content">{{ object.description }}</p>
        <div class="media-body">
            {% for issue in object.issue_set.all %}
            <project class="media content-section">
                {% if issue.owner %}
                <div class="img-with-text">
                    <img class="rounded-circle account-img" src="{{ issue.owner.profile.image.url }}">
                    <small class="text-muted">Owner: {{ issue.owner }}</small>
                </div>
                {% endif %}
                {% for user in issue.users.all %}
                <div class="img-with-text">
                    <img class="rounded-circle small-account-img" src="{{ user.profile.image.url }}">
                    <small class="text-muted">{{ user }}</small>
                </div>
                {% endfor %}
                <div class="media-body">
                    <div class="project-metadata">
                        <a class="mr-2" href="#"><center>Created by {{ issue.creator }}</center></a>
                    </div>
                    <h2 class="project-title"><a href="{% url 'issues:issue-detail' project_id=object.id pk=issue.pk %}"><center>{{ issue.title }}</center></a></h2>
                </div>
            </project>
            {% endfor %}
        </div>
    </div>

</project>
{% endblock content %}

projects/templates/projects/project_form.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% block content %}
<form method="POST">
    {% csrf_token %}
    <fieldset class="form-group">
        <legend class="border-bottom mb-4">New Project</legend>
        {{ form|crispy }}
    </fieldset>
    <div class="form-group">
        <button class="btn btn-outline-info" type="submit">Post</button>
    </div>
</form>
{% endblock content %}

projects/templates/projects/user_projects.html
{% extends "base.html" %}
{% block content %}
<h1>Projects by {{ view.kwargs.username }} <span class="badge badge-secondary">{{ page_obj.paginator.count }}</span></h1>
<div>
    <a class="btn btn-secondary btn-sm mt-1 mb-1" href="{% url 'issues:user-issues' view.kwargs.username %}">{{ view.kwargs.username }}'s Issues</a>
</div>
{% for project in projects %}
<project class="media content-section">
    <img class="rounded-circle account-img" src="{{ project.creator.profile.image.url }}">
    <div class="media-body">
        <div class="project-metadata">
            <a class="mr-2" href="{% url 'projects:user-projects' username=project.creator.username %}">{{ project.creator }}</a>
        </div>
        <h3><a class="project-title" href="{% url 'projects:project-detail' project.pk %}">{{ project.title }}</a></h3>
        <p class="project-content">{{ project.description }}</p>
    </div>
</project>
{% endfor %}
{% if is_paginated %}
    {% if page_obj.has_previous %}
        <a class="btn btn-outline-info mb-4" href="?page=1">First</a>
        <a class="btn btn-outline-info mb-4" href="?page={{ page_obj.previous_page_number }}">Previous</a>
    {% endif %}
    {% for num in page_obj.paginator.page_range %}
        {% if page_obj.number == num %}
            <a class="btn btn-info mb-4" href="?page={{ num }}">{{ num }}</a>
        {% elif num > page_obj.number|add:'-3' and num < page_obj.number|add:'3' %}
            <a class="btn btn-outline-info mb-4" href="?page={{ num }}">{{ num }}</a>
        {% endif %}
    {% endfor %}
    {% if page_obj.has_next %}
        <a class="btn btn-outline-info mb-4" href="?page={{ page_obj.next_page_number }}">Next</a>
        <a class="btn btn-outline-info mb-4" href="?page={{ page_obj.paginator.num_pages }}">Last</a>
    {% endif %}
{% endif %}
{% endblock content %}