issue_tracker/urls.py
from django.conf import settings
from django.conf.urls.static import static

from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as auth_views
from users import views as user_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('issues.urls')),
    path('', include('projects.urls')),
    path('projects/', include('projects.urls')),
    path('users/register/', user_views.register, name='register'),
    path('users/login/', auth_views.LoginView.as_view(template_name='users/login.html'), name='login'),
    path('users/logout/', auth_views.LogoutView.as_view(template_name='users/logout.html'), name='logout'),
    path('password-reset/', auth_views.PasswordResetView.as_view(template_name='users/password_reset.html'),
         name='password_reset'),
    path('password-reset/done/', auth_views.PasswordResetDoneView.as_view(template_name='users/password_reset_done.html'),
         name='password_reset_done'),
    path('password-reset-complete/',
         auth_views.PasswordResetCompleteView.as_view(template_name='users/password_reset_complete.html'),
         name='password_reset_complete'),
    path('password-reset-confirm/confirm/<uidb64>/<token>/',
         auth_views.PasswordResetConfirmView.as_view(template_name='users/password_reset_confirm.html'),
         name='password_reset_confirm'),
    path('users/profile/', user_views.profile, name='profile'),

]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

issues/urls.py
from django.urls import path
from . import views
from .views import (
    IssueDetailView,
    IssueCreateView,
    IssueUpdateView,
    IssueDeleteView,
    UserIssueListView,
    ProjectIssueListView,
    ownership_view,
    load_hours_view,
    close_issue_view,
)
app_name = 'issues'
urlpatterns = [
    path('projects/<int:project_id>/issues/', ProjectIssueListView.as_view(), name='project-issues'),
    path('<str:username>/issues/', UserIssueListView.as_view(), name='user-issues'),
    path('projects/<int:project_id>/issues/<int:pk>/', IssueDetailView.as_view(), name='issue-detail'),
    path('projects/<int:project_id>/issues/new/', IssueCreateView.as_view(), name='issue-create'),
    path('projects/<int:project_id>/issues/<int:pk>/update/', IssueUpdateView.as_view(), name='issue-update'),
    path('projects/<int:project_id>/issues/<int:pk>/delete/', IssueDeleteView.as_view(), name='issue-delete'),
    path('projects/<int:project_id>/issues/<int:pk>/ownership/', ownership_view, name='issue-ownership'),
    path('projects/<int:project_id>/issues/<int:pk>/load-hours/', load_hours_view, name='issue-load-hours'),
    path('projects/<int:project_id>/issues/<int:pk>/close/', close_issue_view, name='issue-close'),

]

projects/urls.py
from django.urls import path
from . import views
from .views import (
    ProjectListView,
    ProjectDetailView,
    ProjectCreateView,
    ProjectUpdateView,
    ProjectDeleteView,
    UserProjectListView
)

app_name = 'projects'
urlpatterns = [
    path('', ProjectListView.as_view(), name='home'),
    path('user/<str:username>/', UserProjectListView.as_view(), name='user-projects'),
    path('<int:pk>/', ProjectDetailView.as_view(), name='project-detail'),
    path('new/', ProjectCreateView.as_view(), name='project-create'),
    path('<int:pk>/update/', ProjectUpdateView.as_view(), name='project-update'),
    path('<int:pk>/delete/', ProjectDeleteView.as_view(), name='project-delete'),
    path('about/', views.about, name='about'),
]

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
          integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="{% static 'main.css' %}">
    {% if title %}
    <title>Django Issue Tracker - {{title}}</title>
    {% else %}
    <title>Django Issue Tracker</title>
    {% endif %}
</head>
<body>
<header class="site-header">
    <nav class="navbar navbar-expand-md navbar-dark bg-steel fixed-top">
        <div class="container">
            <a class="navbar-brand mr-4" href="{% url 'projects:home' %}">Issue Tracker</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarToggle"
                    aria-controls="navbarToggle" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarToggle">
                <div class="navbar-nav mr-auto">
                    <a class="nav-item nav-link" href="{% url 'projects:home' %}">Home</a>
                    <a class="nav-item nav-link" href="{% url 'projects:about' %}">About</a>
                </div>
                <!-- Navbar Right Side -->
                <div class="navbar-nav">
                    {% if user.is_authenticated %}
                    <a class="nav-item nav-link" href="{% url 'issues:user-issues' username=user.username %}">My Issues</a>
                    <a class="nav-item nav-link" href="{% url 'projects:project-create' %}">New Project</a>
                    <a class="nav-item nav-link" href="{% url 'profile' %}">My Profile</a>
                    <a class="nav-item nav-link" href="{% url 'logout' %}">Logout</a>
                    {% else %}
                    <a class="nav-item nav-link" href="{% url 'login' %}">Login</a>
                    <a class="nav-item nav-link" href="{% url 'register' %}">Register</a>
                    {% endif %}
                </div>
            </div>
        </div>
    </nav>
</header>
<main role="main" class="container">
    <div class="row">
        <div class="col-md-8">
            {% if messages %}
            {% for message in messages %}
            <div class="alert alert-{{message.tags}}">
                {{message}}
            </div>
            {% endfor %}
            {% endif %}
            {% block content %}{% endblock %}
        </div>
        <div class="col-md-4">
            <div class="content-section">
                <h3>Sidebar</h3>
                <p class='text-muted'>
                <div class="just-padding">

                    <div class="list-group list-group-root well">

                        <a href="#item-1" class="list-group-item" data-toggle="collapse">
                            <i class="glyphicon glyphicon-chevron-right"></i>Latest Users
                        </a>
                        {% for user in latest_users %}
                        <div class="list-group collapse" id="item-1">
                            <a href="{% url 'projects:user-projects' username=user.username %}" style="text-align: center;" class="list-group-item">
                                <i class="glyphicon glyphicon-chevron-right"></i>{{ user.username }}
                            </a>
                        </div>
                        {% endfor %}
                        <a class="list-group-item" data-toggle="collapse">
                            <i class="glyphicon glyphicon-chevron-right"></i> -
                        </a>
                        <div class="list-group collapse" id="item-2">

                            <a href="#item-2-1" class="list-group-item" data-toggle="collapse">
                                <i class="glyphicon glyphicon-chevron-right"></i>Item 2.1
                            </a>
                            <a href="#item-2-2" class="list-group-item" data-toggle="collapse">
                                <i class="glyphicon glyphicon-chevron-right"></i>Item 2.2
                            </a>
                            <a href="#item-2-3" class="list-group-item" data-toggle="collapse">
                                <i class="glyphicon glyphicon-chevron-right"></i>Item 2.3
                            </a>
                        </div>


                        <a class="list-group-item" data-toggle="collapse">
                            <i class="glyphicon glyphicon-chevron-right"></i> -
                        </a>
                        <div class="list-group collapse" id="item-3">

                            <a href="#item-3-1" class="list-group-item" data-toggle="collapse">
                                <i class="glyphicon glyphicon-chevron-right"></i>Item 3.1
                            </a>
                            <div class="list-group collapse" id="item-3-1">
                                <a href="#" class="list-group-item">Item 3.1.1</a>
                                <a href="#" class="list-group-item">Item 3.1.2</a>
                                <a href="#" class="list-group-item">Item 3.1.3</a>
                            </div>

                            <a href="#item-3-2" class="list-group-item" data-toggle="collapse">
                                <i class="glyphicon glyphicon-chevron-right"></i>Item 3.2
                            </a>
                            <div class="list-group collapse" id="item-3-2">
                                <a href="#" class="list-group-item">Item 3.2.1</a>
                                <a href="#" class="list-group-item">Item 3.2.2</a>
                                <a href="#" class="list-group-item">Item 3.2.3</a>
                            </div>

                            <a href="#item-3-3" class="list-group-item" data-toggle="collapse">
                                <i class="glyphicon glyphicon-chevron-right"></i>Item 3.3
                            </a>
                            <div class="list-group collapse" id="item-3-3">
                                <a href="#" class="list-group-item">Item 3.3.1</a>
                                <a href="#" class="list-group-item">Item 3.3.2</a>
                                <a href="#" class="list-group-item">Item 3.3.3</a>
                            </div>

                        </div>
                </p>
            </div>
        </div>
    </div>
</main>

<!-- Optional JavaScript -->
<!-- jQuery first, then Popper.js, then Bootstrap JS -->
<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
        integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
        crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"
        integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1"
        crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"
        integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM"
        crossorigin="anonymous"></script>

</body>
</html>